version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Build the Docker image
          command: docker build . --file Dockerfile --tag limbo:v2-$(date +%s)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build