version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:lts

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --verbose --no-cache
      - run:
          name: Deploy Prisma
          command: npm run generate
      - run:
          name: Build
          command: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build